version: "3"

services:
  cloudflared:
    container_name: cloudflared_doh
    image: visibilityspots/cloudflared:arm
    restart: always
    networks:
      pihole_net:
        ipv4_address: 10.0.0.2

  pihole:
    container_name: pihole_doh
    image: pihole/pihole:${PIHOLE_TAG}
    restart: always
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "${IP_ADDR}:53:53/tcp"
      - "${IP_ADDR}:53:53/udp"
    cap_add:
      - NET_ADMIN
    environment:
      DNS1: '10.0.0.2#5054'
      DNS2: 'no'
      IPv6: 'false'
      TZ: 'America/New_York'
      DNSMASQ_LISTENING: 'all'
      WEBPASSWORD: '${ADMIN_PASSWORD}'
    # Add your own custom hostnames you need for your domain
    extra_hosts:
      - 'udm.wysechoice.net udm:192.168.1.1'
      - 'pi-hole.wysechoice.net pi-hole:192.168.1.2'
    networks:
      pihole_net:
        ipv4_address: 10.0.0.3
    dns:
      - 127.0.0.1
      - 1.1.1.1
    volumes:
      - 'pihole_etc:/etc/pihole/'
      - 'pihole_dnsmasq:/etc/dnsmasq.d/'
      - '/pihole_certs:/etc/certs/:ro'
      - './external.conf:/etc/lighttpd/external.conf'

  letsencrypt:
    container_name: letsencrypt_doh
    #image: adferrand/letsencrypt-dns:${LE_TAG}
    image: cwyse/letsencrypt-dns:armv7l-latest
    environment:
      LETSENCRYPT_USER_MAIL: '${EMAIL}'
      LEXICON_PROVIDER: 'cloudflare'
      LETSENCRYPT_SKIP_REGISTER: 'false'
      DEPLOY_HOOK: 'gen_certs.sh'
      CERTS_USER_OWNER: '33'
      CERTS_GROUP_OWNER: '33'
      LETSENCRYPT_STAGING: '${LE_STAGING}'
    volumes:
      - ./le-domains.conf:/etc/letsencrypt/domains.conf
      - ./gen_certs.sh:/usr/local/bin/gen_certs.sh
      - /var/run/docker.sock:/var/run/docker.sock
      - le_certs:/etc/letsencrypt
      - /pihole_certs:/pihole_certs
    restart: always

volumes:
  pihole_etc:
  pihole_dnsmasq:
  le_certs:
  pihole_certs:

networks:
  pihole_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/29
